### ISSUE TITLE
Inconsistent licensing

### ISSUE THREAD

**Issue by gnustavo** [marioct/sms-send-facilitamovel#1]
Hi Mario,

The LICENSE file in the repository contains the Apache License.

The dist.ini, the README.pod, and the Facilitamovel.pm files say that the module is licensed with the Perl license.

The META.yml says that the license is 'unknown'.

They all should agree to one license, no?

**Comment by marioct-zz** [comment]
Yes, Perl license i guess.
The Apache License was generated by h2xs tool.
I have to discover how to fix that automagically
I trying to use Dzil

**Comment by gnustavo** [comment]
OK. I'll make a pr to fix this. Later we can work on the dzil configuration.
